// Auto-generated by gen2.ts
import { DatabaseSync } from "node:sqlite";

export interface Users {
    id?: number;
    name: string;
}

export async function GetUser(db: DatabaseSync): Promise<Users | undefined> {
    const stmt = db.prepare(`SELECT * FROM users`);
    return stmt.get() as Users | undefined;
}

export async function CreateUser(db: DatabaseSync, p0: any): Promise<void> {
    const stmt = db.prepare(`INSERT INTO users (name)
VALUES (?)`);
    stmt.run(p0);
}

